apiVersion: v1
kind: Service
metadata:
  name: express-api-service
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort  # Use LoadBalancer to expose the service externally