apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-deployment
  labels:
    app: express-api
spec:
  replicas: 1  # Number of replicas (pods)
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: muhohoweb/express-api:1.0.1  # Use the appropriate image tag
          ports:
            - containerPort: 3000  # The port that the container listens on
